#// create a job dynamically in jenkins
- name: Install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    state: latest
    executable: pip3.9

- name: add jobs on jenkins
  ansible.builtin.template:
    src: pipeline.xml
    dest: /tmp/{{item}}.xml
  loop:
    - frontend
    - backend

- name: create a jobs on jenkins dashboard
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline.xml') }}"
    name: "{{ item }}"
    password: "{{ secrets.jenkins_password}}"
    url: http://jenkins-internal.pdevops72.online:8080/
    user: "{{ secrets.jenkins_username }}"
  loop:
    - frontend
    - backend