- name: get secrets from vault
  ansible.builtin.debug:
    msg: "username: {{secrets.jenkins_username}}, password: {{secrets.jenkins_password}}"

- name: include jenkins setup
  ansible.builtin.include_tasks:
    file: jenkins_setup.yml
  when: jenkins_setup | bool

- name: include jenkins jobs
  ansible.builtin.include_tasks:
    file: jenkins_job.yml
  when: jenkins_job | bool








