- name: copy jenkins repo
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: install java and jenkins
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
      - jenkins
    state: installed

- name: start jenkins
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    daemon-reload: yes
    enabled: yes


# add groovy script for to skip initialization on jenkins dashboard before login
- name: make a groovy directory
  ansible.builtin.file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory

- name: copy groovy scripts
  ansible.builtin.template:
    src: "{{item}}"
    dest: /var/lib/jenkins/init.groovy.d/{{item}}
  loop:
    - wizard.groovy
    - plugins.groovy
    - admin-user.groovy

# create jobs on jenkins dashboard


