- name: jenkins job
  ansible.builtin.template:
    src: templates/jobs/webhook.xml
    dest: /tmp/{{item}}.xml
  loop:
    - frontend
    - catalogue
    - user
    - cart
    - shipping
    - payment


- name: install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    executable: pip3.9

# create jobs on jenkins dashboard
- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: "{{ item }}"
    password: admin123
    url: http://jenkins-internal.pdevops78.online:8080
    user: admin
  loop:
    - frontend
    - catalogue
    - user
    - cart
    - shipping
    - payment
